/*
 * Copyright 2018 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

import java.util.List;

global List list

rule "Say hello" @Propagation(IMMEDIATE)
    salience 11
when
then
    String s = "Hello. Rule executed from " + System.getProperty("org.kie.server.location", "unknow location");
    System.out.println(s);
    list.add(s);
end

rule "Say world" @Propagation(IMMEDIATE)
    salience 10
when
then
    String s = "World. Rule executed from " + System.getProperty("org.kie.server.location", "unknow location");
    System.out.println(s);
    list.add(s);
end
