#!/bin/sh

echo Congratulations! You\'ve just made a commit! Time for a break. >> /opt/eap/standalone/data/kie/git/hooks/out.txt
date +%Y-%m-%d\ %H:%M:%S >> /opt/eap/standalone/data/kie/git/hooks/out.txt